### ISSUE TITLE
please make an AAX version of this, you're great!!!

### ISSUE THREAD

**Issue by Rikademus** [RitaAndAurora/ddrm-jfsebastian#1]
please make an AAX version of this, you're great!!!

**Comment by ffont** [comment]
hi, thanks for your comment.
I'll investigate and see if I can do that for a coming release.

**Comment by Rikademus** [comment]
Thanks, to clarify I meant AAX DSP..

Rik Simpson

Website: www.riksimpson.com
Twitter: https://twitter.com/rikademus

**Comment by ffont** [comment]
To do AAX and and publish it looks like I need to get some certificate from AVID which involves some paperwork and even an exam (WTF!). I don't have the bandwidth to do this right now. However, if things change somehow in the future I'll definitely publish as AAX as well.
