### ISSUE TITLE
Midi Port Scanning OFF, Midi Out still won't stick

### ISSUE THREAD

**Issue by STk3000** [RitaAndAurora/ddrm-jfsebastian#3]
Hello,

I have this issue, with DD connected via USB only, JFS will not stick to midi out settings.

If I select any other Midi Out port, it will stick but if i select the USB MIdi Out Deckard's Dream it will just revert very fast to not having anything setup.

I have disabled Port scanning still issue persists.

I am on Mac, Ableton latest version, DD hw rev 1.0 and fw 1.3

You can use my device for debugging.

Catalin

**Comment by ffont** [comment]
Thanks for reporting. Another user reported this issue and I implemented a fix which seemed to work. Can you test if the error also happens with this build of J.F. Sebastian: https://www.dropbox.com/sh/e4o85ezertx639d/AACPGMpQAxs3wr-lDRSbbhJya?dl=1 ? (just use the standalone version for a quick test, or install the plugins manually as per instructions in the zip file). Le me know...

**Comment by STk3000** [comment]
can confirm it works now thanks

**Comment by ffont** [comment]
Great, closing this issue then. Thanks for testing!
