### ISSUE TITLE
"Zoom" resizing unreachable on 2013 MacBook Air

### ISSUE THREAD

**Issue by trevornoble** [RitaAndAurora/ddrm-jfsebastian#4]
The zoom button can't be reached because the app has a fixed size. My 2013 MacBook Air's resolution is capped at 1440x900, which prevents me from resizing as the zoom button sits just out of frame. 

I recommend moving the settings button to the top of the app to be more accessible.

![Screen Shot 2020-08-03 at 13 23 26](https://user-images.githubusercontent.com/33359157/89223962-8c0cac80-d58c-11ea-8755-2fc227486e58.png)

**Comment by trevornoble** [comment]
I guess it's easy enough to tab through the options after clicking on the app to find the settings menu. closing out.

**Comment by ffont** [comment]
This issue has been reported by many users, the new version (to come out in the coming 1-2 months) will feature this change. Meanwhile you can do workarounds like changing scaling of the screen and setting new zoom level (JF will remember the latest selected zoom when you close/open again), or maybe this "tab" thing which I have not really tried.
