### ISSUE TITLE
Incorrect Repository Name in README

### ISSUE THREAD

**Issue by eltobosolo** [RitaAndAurora/ddrm-jfsebastian#9]
In https://github.com/RitaAndAurora/ddrm-jfsebastian/blob/master/README.md the instructions for getting the source has the following command line:

`git clone https://github.com/RitaAndAurora/kijimi-babu-frik.git && cd kijimi-babu-frik.git && git submodule update --init`

i.e. the repository points to the kijimi plugin not jfsebastian.

**Comment by eltobosolo** [comment]
I think there's also a spurious `.git` suffix in the second line.  The command line should be:

`git clone https://github.com/RitaAndAurora/ddrm-jfsebastian.git && cd ddrm-jfsebastian && git submodule update --init`

**Comment by ffont** [comment]
I'll fix that, thanks!
